name: Documentation
on:
  push:
    branches:
      - master
jobs:
  build:
    name: DocFX generation
    runs-on: ubuntu-latest
    steps:
    - uses: nikeee/docfx-action@v1.0.0
      name: Build documentation
      with:
        args: docs/docfx.json
    - uses: maxheld83/ghpages@master
      name: Publish documentation
      env:
        BUILD_DIR: docs/_site
        GH_PAT: ${{ secrets.GH_PAT }}