name: Documentation
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout documentation branch
      uses: actions/checkout@v1
      with:
        ref: documentation
        path: docs
    - name: Checkout master branch
      uses: actions/checkout@v1
      with:
        ref: master
        path: docs/src
    - name: Change directory
      run: cd ..
    - uses: nikeee/docfx-action@v1.0.0
      name: Build documentation
      with:
        args: docfx.json
    - uses: maxheld83/ghpages@master
      name: Publish documentation
      env:
        BUILD_DIR: _site
        GH_PAT: ${{ secrets.GH_PAT }}